version: '3.1'
services:
  db:
    image: mariadb
    volumes:
      - imponodata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
  app:
    image: digitalist/impono
    ports:
      - "80:80"
    environment:
      DATABASE_PASSWORD: password
      DATABASE_USER: root
      DATABASE_HOST: db
      DATABASE_NAME: impono_db
      SYMFONY_ENV: prod
      ENV: prod
      TZ: "Europe/Stockholm"
    volumes:
      - imponoconfig:/var/www/app/config
volumes:
  imponodata:
  imponoconfig:
