fos_http_cache:
#    cache_control:
#        defaults:
#            overwrite: true
#        rules:
#            -
#                match:
#                    attributes: { _route: "get_container_javascript" }
#                headers:
#                    cache_control: { public: true, max_age: 300, s_maxage: 500 }
