services:
    seven_tag_variable.repository.variable_repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
        arguments:
            - SevenTag\Api\VariableBundle\Entity\Variable
    seven_tag_variable.repository.variable_type_repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ '@doctrine.orm.default_entity_manager' , getRepository ]
        arguments:
            - SevenTag\Api\VariableBundle\Entity\VariableType
