parameters:
    database_driver: pdo_mysql
    database_port: null
    database_host: '%env(DATABASE_HOST)%'
    env(DATABASE_HOST): db
    database_name: '%env(DATABASE_NAME)%'
    env(DATABASE_NAME): impono_db
    database_user: '%env(DATABASE_USER)%'
    env(DATABASE_USER): root
    database_password: '%env(DATABASE_PASSWORD)%'
    env(DATABASE_PASSWORD): password
    database_path: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    mailer_sender: example@example.com
    mailer_spool: { type: file, path: '%kernel.root_dir%/../var/spool' }
    mailer_delivery_address: null
    locale: en
    secret: '&-2_W\$/N=auNLuE?NM6:G:w-V{5,_'
    datetime_default_format: 'Y-m-d\TH:i:sO'
    seventag_licence_template_path: '%kernel.root_dir%/Resources/container-lib/licence.dist'
    seventag_tagtree_template_path: '%kernel.root_dir%/Resources/container-lib/tagTree.js.dist'
    seventag_tagtree_sync_template_path: '%kernel.root_dir%/Resources/container-lib-sync/tagTree.js.dist'
    seventag_javascript_debugger_path: '%kernel.root_dir%/../web/container-debugger/debug.js'
    seventag_domain: //localhost
    seventag_javascript_library_path: '%kernel.root_dir%/Resources/container-lib/library.js.dist'
    seventag_javascript_library_sync_path: '%kernel.root_dir%/Resources/container-lib-sync/library.js.dist'
    seventag_javascript_bootstrap_path: '%kernel.root_dir%/Resources/container-lib/bootstrap.js.dist'
    seventag_javascript_bootstrap_sync_path: '%kernel.root_dir%/Resources/container-lib-sync/bootstrap.js.dist'
    seventag_javascript_cache_dir: '%kernel.root_dir%/../web/containers'
    seventag_javascript_url_template: //yourcdnhostname.com/containers/@id@.js
    seventag_javascript_synchronous_url_template: //yourcdnhostname.com/containers/@id@.sync.js
    seventag_javascript_noscript_url_template: //yourcdnhostname.com/containers/@id@/noscript.html
    seventag_container_library_cdn: { enabled: false, service: null, service_options: {  } }
    sentry_dsn: null
    web_dir: '%kernel.root_dir%/../web'
    oauth2_secret: 2qfeiethyyiowogg808c0co8wokks4w8gk8ow8sccco888s8w4
    random_id: tfdhlzbvetc4gssc4wwgk8s08koc80sow8s4scoc4owgoc0w8

