mysql:
    container_name: mysql
    net: seventag_net
    image: mysql:5.6
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: impono
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    volumes:
        - /var/lib/mysql:/var/lib/mysql
        - /var/log/mysql:/var/log/mysql

php:
    container_name: php
    net: seventag_net
    build: php
    ports:
        - 80:80
    volumes:
        - /var/www/impono:/var/www/impono
        - /var/log/apache2/:/var/log/apache2

firefox:
    container_name: firefox
    net: seventag_net
    image: selenium/standalone-firefox-debug
    ports:
        - 4444:4444

chrome:
    container_name: chrome
    net: seventag_net
    image: selenium/standalone-chrome-debug
    ports:
        - 4445:4444
