services:
    seven_tag_tag.repository.tag_repository:
        class: SevenTag\Api\TagBundle\Entity\TagRepository
        factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
        arguments:
            - SevenTag\Api\TagBundle\Entity\Tag
