services:

  seven_tag_container.container_library_sync.template_loader.licence_loader:
      class: SevenTag\Api\ContainerBundle\ContainerLibrary\Template\Loader\FileLoader
      public: false
      arguments: ['%seventag_licence_template_path%']

  seven_tag_container.container_library_sync.template_loader.tag_tree_loader:
      class: SevenTag\Api\ContainerBundle\ContainerLibrary\Template\Loader\FileLoader
      public: false
      arguments: ['%seventag_tagtree_sync_template_path%']

  seven_tag_container.container_library_sync.template_loader.library_loader:
    class: SevenTag\Api\ContainerBundle\ContainerLibrary\Template\Loader\FileLoader
    public: false
    arguments: ['%seventag_javascript_library_sync_path%']

  seven_tag_container.container_library_sync.container_bootstrap.template_loader.library_loader:
    class: SevenTag\Api\ContainerBundle\ContainerLibrary\Template\Loader\FileLoader
    public: false
    arguments: ['%seventag_javascript_bootstrap_sync_path%']

  seven_tag_container.container_library_sync.template_loader.container_debugger:
    class: SevenTag\Api\ContainerBundle\ContainerLibrary\Template\Loader\FileLoader
    public: false
    arguments: ['%seventag_javascript_debugger_path%']

  seven_tag_container.container_library_sync.template_loader:
    class: SevenTag\Api\ContainerBundle\ContainerLibrary\Template\Loader\ChainLoader
    calls:
      - [ add, ['@seven_tag_container.container_library_sync.template_loader.licence_loader', 5] ]
      - [ add, ['@seven_tag_container.container_library_sync.template_loader.tag_tree_loader', 4] ]
      - [ add, ['@seven_tag_container.container_library_sync.template_loader.library_loader', 3] ]
      - [ add, ['@seven_tag_container.container_library_sync.container_bootstrap.template_loader.library_loader', 1] ]
      - [ add, ['@seven_tag_container.container_library_sync.template_loader.container_debugger', 0] ]

  seven_tag_container.container_library_sync.template_handler.debugger:
    class: SevenTag\Api\ContainerBundle\ContainerLibrary\Template\Handler\DebuggerHandler
    arguments: ['@seven_tag_container.mode_resolver']
    public: false

  seven_tag_container.container_library_sync.template_handler.tag_tree:
    class: SevenTag\Api\ContainerBundle\ContainerLibrary\Template\Handler\TagTreeHandler
    public: false
    arguments: ['@seven_tag_container.tag_tree_builder_sync']

  seven_tag_container.container_library_sync.template_handler.containerjs:
    class: SevenTag\Api\ContainerBundle\ContainerLibrary\Template\Handler\ContainerJsHandler
    arguments: ['%seventag_domain%']
    public: false

  seven_tag_container.container_library_sync.template_handler.variables:
    class: SevenTag\Api\ContainerBundle\ContainerLibrary\Template\Handler\VariablesHandler
    arguments: ['@seven_tag_variable.variable_manager', '@jms_serializer.serializer']
    public: false

  seven_tag_container.container_library_sync.template_handler.containerjs_config:
    class: SevenTag\Api\ContainerBundle\ContainerLibrary\Template\Handler\ContainerjsConfigHandler
    arguments: ['@seven_tag_container.container_library.config_provider.plugins_manifest_provider']
    public: false

  seven_tag_container.container_library_sync.template_handler:
    class: SevenTag\Api\ContainerBundle\ContainerLibrary\Template\Handler\ChainHandler
    calls:
      - [ add, ['@seven_tag_container.container_library_sync.template_handler.debugger', 1] ]
      - [ add, ['@seven_tag_container.container_library_sync.template_handler.tag_tree', 2] ]
      - [ add, ['@seven_tag_container.container_library_sync.template_handler.containerjs', 1] ]
      - [ add, ['@seven_tag_container.container_library_sync.template_handler.variables', 2] ]
      - [ add, ['@seven_tag_container.container_library_sync.template_handler.containerjs_config', 1] ]

  seven_tag_container.container_library_sync_privacy.template_handler:
    class: SevenTag\Api\ContainerBundle\ContainerLibrary\Template\Handler\ChainHandler
    calls:
      - [ add, ['@seven_tag_container.container_library_sync.template_handler.debugger', 1] ]
      - [ add, ['@seven_tag_container.container_library_sync.template_handler.tag_tree', 2] ]
      - [ add, ['@seven_tag_container.container_library_sync.template_handler.containerjs', 1] ]
      - [ add, ['@seven_tag_container.container_library_sync.template_handler.variables', 2] ]
      - [ add, ['@seven_tag_container.container_library.template_handler.optout_config', 1] ]

  seven_tag_container.container_library_sync.generator:
    class: SevenTag\Api\ContainerBundle\ContainerLibrary\Generator\TemplateGenerator
    arguments: ['@seven_tag_container.container_library_sync.template_loader', '@seven_tag_container.container_library_sync.template_handler']

  seven_tag_container.container_library_sync_privacy.generator:
    class: SevenTag\Api\ContainerBundle\ContainerLibrary\Generator\TemplateGenerator
    arguments: ['@seven_tag_container.container_library_sync.template_loader', '@seven_tag_container.container_library_sync_privacy.template_handler']

  seven_tag_container.subscriber.sync.storage_javascript_in_filesystem_subscriber:
    class: SevenTag\Api\ContainerBundle\ContainerLibrary\Subscriber\StorageJavascriptInFilesystemSubscriber
    arguments: [ '@seven_tag_container.container_library_sync.generator', '@gaufrette.container_library', '%s.sync.js', '@?seven_tag_container.container_library.cdn' ]
    tags:
      - { name: kernel.event_subscriber }

  seven_tag_container.subscriber.sync_privacy.storage_javascript_in_filesystem_subscriber:
    class: SevenTag\Api\ContainerBundle\ContainerLibrary\Subscriber\StorageJavascriptInFilesystemSubscriber
    arguments: [ '@seven_tag_container.container_library_sync_privacy.generator', '@gaufrette.container_library', '%s.privacy.sync.js', '@?seven_tag_container.container_library.cdn' ]
    tags:
      - { name: kernel.event_subscriber }
