services:
    seven_tag_container.repository.container_repository:
        class: SevenTag\Api\ContainerBundle\Entity\ContainerRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - SevenTag\Api\ContainerBundle\Entity\Container

    seven_tag_container.repository.container_permissions_repository:
        class: SevenTag\Api\ContainerBundle\Entity\ContainerPermissionRepository
        factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
        arguments:
            - SevenTag\Api\ContainerBundle\Entity\ContainerPermission
