---
# Install and configure MailHog.
- name: Ensure mailhog install directory exists.
  file:
    path: "{{ mailhog_install_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0755
  become: true

- name: Download MailHog and mhsendmail binaries.
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - url: "{{ mailhog_binary_url }}"
      dest: "{{ mailhog_install_dir }}/mailhog"
    - url: "{{ mhsendmail_binary_url }}"
      dest: "{{ mailhog_install_dir }}/mhsendmail"
  become: true

- name: Copy mailhog init script into place.
  template:
    src: mailhog.init.j2
    dest: /etc/init.d/mailhog
    owner: root
    group: root
    mode: 0755
  become: true

- name: Copy mailhog systemd unit file into place (for systemd systems).
  template:
    src: mailhog.unit.j2
    dest: /etc/systemd/system/mailhog.service
    owner: root
    group: root
    mode: 0755
  when: >
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version.split(".")[0]|int >= 16) or
    (ansible_distribution == 'Debian' and ansible_distribution_version.split(".")[0]|int >= 8) or
    (ansible_distribution == 'CentOS' and ansible_distribution_version.split(".")[0]|int >= 7) or
    (ansible_distribution == 'Fedora')
  become: true

- name: Ensure mailhog is enabled and will start on boot.
  service: name=mailhog state=started enabled=yes
  become: true

- name: check for sendmail path in php.ini for mailhog
  lineinfile: dest=/etc/php.ini line='sendmail_path = "/opt/mailhog/mhsendmail"'
  become: true

