---
- name: Installing php 7.0 and modules.
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php71w
    - php71w-cli
    - php71w-common
    - php71w-curl
    - php71w-pecl-imagick
    - php71w-json
    - php71w-soap
    - php71w-mcrypt
    - php71w-mysql
    - php71w-xml
    - php71w-xmlrpc
    - php71w-devel
    - php71w-mbstring
    - php71w-gd
    - php71w-opcache
    - php71w-bcmath
  become: true

- name: Copy apache php.ini.
  template:
    src: php.digitalist.php.ini.j2
    dest: /etc/php.d/digitalist.php.ini
  become: true
