services:
    seven_tag_user.form_type.create_form_type:
        class: SevenTag\Api\UserBundle\Form\CreateType
        parent: seven_tag_user.form_type.edit_form_type
        tags:
            - { name: form.type }

    seven_tag_user.form_type.edit_form_type:
        class: SevenTag\Api\UserBundle\Form\EditType
        arguments: ['@seven_tag_user.role_list_provider']
        tags:
            - { name: form.type }

    seven_tag_user.form_type.others_settings_form_type:
            class: SevenTag\Api\UserBundle\Form\OthersSettingsType
            arguments: ['@seven_tag.language.language_provider']
            tags:
                - { name: form.type }

    seven_tag_user.form_type.me_form_type:
        class: SevenTag\Api\UserBundle\Form\MeType
        tags:
            - { name: form.type }
