services:
    seven_tag_user.repository.user_repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
        arguments:
            - SevenTag\Api\UserBundle\Entity\User
