SevenTag\Api\TriggerBundle\Entity\Condition:
  type: entity
  table: '`condition`'
  repositoryClass: SevenTag\Api\TriggerBundle\Entity\TriggerRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    variable:
      type: string
      length: 255
    condition:
      column: '`condition`'
      type: string
      length: 255
    value:
      type: string
      length: 255
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
       type: datetime
       gedmo:
        timestampable:
          on: update
  manyToOne:
    trigger:
      targetEntity: SevenTag\Api\TriggerBundle\Entity\Trigger
      inversedBy: conditions
      joinColumn:
        name: trigger_id
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE
        onUpdate: CASCADE
