services:
    clearcode_tag_manager_test.client.cookiejar:
        class: '%test.client.cookiejar.class%'

    clearcode_tag_manager_test.client_history:
        class: '%test.client.history.class%'

    clearcode_tag_manager_test.client:
        class: '%test.client.class%'
        arguments: ['@kernel', '%test.client.parameters%', '@clearcode_tag_manager_test.client_history', '@clearcode_tag_manager_test.client.cookiejar', '@test.session.listener']
