services:
    seven_tag_security.repository.access_token_repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
        arguments:
            - SevenTag\Api\SecurityBundle\Entity\AccessToken
    seven_tag_security.repository.integration_repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ '@doctrine.orm.default_entity_manager' , getRepository ]
        arguments:
            - SevenTag\Api\SecurityBundle\Entity\Integration
